package models;

import com.fasterxml.jackson.databind.ObjectMapper;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.UUID;

public abstract class Booking extends Model {


    public static final String USER_ID_FIELD = "customerId";
    public static final String TESTING_SITE_ID_FIELD = "testingSiteId";

    public static final String SMS_PIN_FIELD = "smsPin";
    public static final String START_TIME_FIELD = "startTime";
    public static final String NOTES_FIELD = "notes";
    public static final String ADDITIONAL_INFO_FIELD = "additionalInfo";
    public static final String QR_CODE_FIELD = "QRCode";
    public static final String URL_FIELD = "url";
    public static final String HAS_RAT_KIT_FIELD = "hasRATKit";

    protected String generateQRCode() {
        //Unique QR Code ( We assume that the QR code will be generated by the third party system)
        // here we just use UUID in java to emulate the QR code
        String uuid = UUID.randomUUID().toString();

        return uuid;
    }

    protected String generateURL() {
        // Unique url ( We assume that the QR code will be generated by the third party system)
        //  here we just use UUID in java to emulate the QR code
        String uuid = UUID.randomUUID().toString();
        String url = "https://Dummy URL/... - " + uuid;
        return url;
    }

    public String getURL() {
        try {
            return entityInfo.findValue(URL_FIELD).asText();
        } catch (NullPointerException e) {
            return null;
        }
    }

    public String getQRCode() {
        try {
            return entityInfo.findValue(QR_CODE_FIELD).asText();
        } catch (NullPointerException e) {
            return null;
        }
    }

    public String getPinCode(){
        try{
            return entityInfo.get(SMS_PIN_FIELD).asText();
        }catch(NullPointerException e){
            return null;
        }

    }

    public void setNode(String node){
        entityInfo.put(NOTES_FIELD, node);
    }

    protected void setSchema(String customerId, String testingSiteId){
        entityInfo.put(USER_ID_FIELD, customerId);
        entityInfo.put(TESTING_SITE_ID_FIELD, testingSiteId);

        String url = generateURL();
        String QRCode = generateQRCode();
        additionalInfo.put(QR_CODE_FIELD, QRCode);
        additionalInfo.put(URL_FIELD, url);

        String time = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date(System.currentTimeMillis()));
        entityInfo.put(START_TIME_FIELD, time);

    }


}
